### ISSUE TITLE
Not generate "*-san" folder in out

### ISSUE THREAD

**Issue by Klavishnik** [0xricksanchez/AFL_Runner#31]
![image](https://github.com/0xricksanchez/AFL_Runner/assets/18628960/8e841ace-9ad3-46d9-99d2-93e4fe1cc04f)

**Comment by 0xricksanchez** [comment]
I guess that is currently expected. The naming could be improved I guess to make this clearer. 

As for the specific example: The ASAN binary is currently only used for the main (first) instance of fuzzing. Hence, the directory will be `main_xmllint_instr_2_10`.
