### ISSUE TITLE
tui bug 

### ISSUE THREAD

**Issue by zerokay** [0xricksanchez/AFL_Runner#34]
Hi, I used the command aflr run --config/AFLR_CFG_XPDF.toml to run it, and after successfully starting, I used aflr tui ./out to check the status. However, it prompts that no fuzzers alive, but I confirmed that the processes do exist.
2024-09-04 11:38:04] - No fuzzers alive. Skipping data collection                                                              │
  │[2024-09-04 11:38:03] - No fuzzers alive. Skipping data collection                                                              │
  │[2024-09-04 11:38:02] - No fuzzers alive. Skipping data collection                                                              │
  │[2024-09-04 11:38:01] - No fuzzers alive. Skipping data collection                                                              │
  │[2024-09-04 11:37:59] - No fuzzers alive. Skipping data collection                                                              │
  │[2024-09-04 11:37:59] - No fuzzers alive                                                                                        │
  │[2024-09-04 11:37:59] - Attempted to fetch PIDs from fuzzer_stats files                                                         │
  │[2024-09-04 11:37:59] - Initialized TUI

**Comment by 0xricksanchez** [comment]
@zerokay Sorry for the delay, I'll start looking into this a bit more in the following days

**Comment by 0xricksanchez** [comment]
@zerokay Does the example at least work for you? Because that one works for me. I don't know how you configured XPDF. If you're able to share your full setup I can look into this a little more
