### ISSUE TITLE
Allow to run all instances with the default settings

### ISSUE THREAD

**Issue by wizche** [0xricksanchez/AFL_Runner#40]
Allow to run all instances with the defaults flags/options

**Comment by 0xricksanchez** [comment]
@wizche what defaults are you interested in? AFLRunner aims to provide the best in slot configuration for a given campaign.

**Comment by wizche** [comment]
Hello @0xricksanchez, sorry for popping all the issues together... 
With defaults I really mean without specifying any power scheduler, queue selection, mutation strategy, ... 
I will try to work on them also myself and hopefully submit a PR once I get to know a bit better Rust :)
Amazing work btw
