### ISSUE TITLE
tmux sends the keys to the window before the shell finishes loading

### ISSUE THREAD

**Issue by wizche** [0xricksanchez/AFL_Runner#42]
Resulting in the instance not starting properly. maybe should we add a sleep?

**Comment by 0xricksanchez** [comment]
The TMUX/Screen interaction can indeed be a little finicky. It seemed to work fine on my end and I already experimented with some sleeps before but wasn’t quite satisfied with my approach. Happy to review a PR regarding that as well

**Comment by wizche** [comment]
What I do now is send a `tmux send-keys -t $SESSION_NAME:$WINDOW_NAME "" C-m` before the actual afl-fuzz command, that seems to fix the problem in my case. 
Here some ChatGPT suggestions:
- Set a flag in `.bashrc` 
```
# Signal that the shell is ready for tmux commands
if [ -n "$TMUX" ]; then
  tmux wait-for -S shell_ready
fi
```
And wait for it: `tmux wait-for shell_ready `

- Read the content from the session until it makes sense:
```bash
# Start a new tmux session
tmux new-session -d -s mysession

# Function to check if the target pane is ready
check_pane_ready() {
    tmux send-keys -t mysession "pwd" C-m  # Run a harmless command
    sleep 0.1  # Small delay to give tmux time to process
    # Capture the last output from the pane
    last_output=$(tmux capture-pane -t mysession -p -S -1)
    
    # Check if the output of 'pwd' was captured (or other suitable prompt check)
    [[ -n "$last_output" ]]
}

# Loop until the shell prompt is ready
until check_pane_ready; do
    sleep 0.1  # Retry interval
done
```

---
Not sure which want you wanna go, maybe keeping a sleep is enough? 
We don't actually care if the whole campaign start is delayed for a second.
