### ISSUE TITLE
Error running TUI: 'Argument list too long (os error 7)'

### ISSUE THREAD

**Issue by wizche** [0xricksanchez/AFL_Runner#43]
Its failing when the fuzzing campaign generates big command lines (e.g. when u have big `AFL_QEMU_INST_RANGES`).
My suggestion is, instead of executing the whole tmux/screen script directly as bash argument, to save it to a named temporary file and execute the file instead. This way it would also make it more "introspectable".

What do you think?

**Comment by 0xricksanchez** [comment]
Yeah I guess that indicates a deeper underlying design issue. I’ll try to review the current implementation asap.

**Comment by wizche** [comment]
Here is how I circumvented it for now: https://github.com/wizche/AFL_Runner/commit/b29e3d4de861c1e8396607da09eeb3dd5090f324

**Comment by 0xricksanchez** [comment]
Seems reasonable to do for now. Happy to patch it in with a PR :)
