### ISSUE TITLE
Allow to specify a seed for the random generator

### ISSUE THREAD

**Issue by wizche** [0xricksanchez/AFL_Runner#49]
This way we can get predictable distribution of flags/options.

Something like:
```toml
# Seed
seed = 42
```

**Comment by 0xricksanchez** [comment]
I guess we could do that, not sure what the exact benefits will be like (except the predictable distribution and, as a result, an easier way to write some unit-tests). I'm not opposed to add this and swapping the (apparently deprecated `thread_rng` [[ref](https://rust-random.github.io/rand/rand/fn.thread_rng.html)]) with a `SeedableRng` ([Ref.](https://rust-random.github.io/rand/rand/trait.SeedableRng.html))

**Comment by wizche** [comment]
Yeah, it would be nice to test the commands generation

**Comment by 0xricksanchez** [comment]
Adding tests should now be easier. New tests can be added in each dedicated PR. A baseline test-suite for existing code can be implemented via #27
